version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=order_service_db
      - MYSQL_USER=wa2_user
      - MYSQL_PASSWORD=uJ47J76Ar7nHib4Nqy3J
    volumes:
      - /data/mysql
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9100:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka

  orchestrator:
    build:
      context: ./orchestrator
    depends_on:
      - kafka
      - mysql-docker-container
    ports:
      - "8083:8083"

  order:
    image: order-image
    build:
      context: ./orderService
    depends_on:
      - kafka
      - mysql-docker-container
    ports:
      - "8081:8081"
volumes:
  zookeeper_data:
  kafka_data: