server:
  port: 8083
---
spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: order-created
    processor-out-0:
      destination: order-updated
---
service:
  endpoints:
    warehouse: http://localhost:8084
    wallet: http://localhost:8082